-- A1.1 Lektion 2: Befinden, Familie, Verben, Pronomen, Zahlen, Sätze
-- Kann eigenständig ausgeführt werden, um Lektion 2 (A1.1) zu befüllen oder zurückzusetzen.

DELETE FROM public.vocabulary_cards
WHERE level = 'A1.1' AND lesson = 'Lektion 2';

INSERT INTO public.vocabulary_cards
  (lesson, level, word_de, article, plural, translation_ru, translation_tr, translation_en, is_hard_for_ru, is_hard_for_tr)
VALUES
-- Befinden
('Lektion 2', 'A1.1', 'Wie geht''s?', 'none', NULL, 'Как дела?', 'Nasılsın? / Nasıl gidiyor?', 'How''s it going?', false, false),
('Lektion 2', 'A1.1', 'Wie geht es dir?', 'none', NULL, 'Как у тебя дела?', 'Nasılsın?', 'How are you? (informal)', false, false),
('Lektion 2', 'A1.1', 'Wie geht es Ihnen?', 'none', NULL, 'Как у вас дела?', 'Nasılsınız?', 'How are you? (formal)', false, false),
('Lektion 2', 'A1.1', 'Danke, gut.', 'none', NULL, 'Спасибо, хорошо.', 'Teşekkürler, iyiyim.', 'Thanks, I''m well.', false, false),
('Lektion 2', 'A1.1', 'sehr gut', 'none', NULL, 'очень хорошо', 'çok iyi', 'very good', false, false),
('Lektion 2', 'A1.1', 'super', 'none', NULL, 'супер', 'süper', 'great', false, false),
('Lektion 2', 'A1.1', 'Es geht.', 'none', NULL, 'Нормально. / Пойдёт.', 'İdare eder.', 'So-so.', false, false),
('Lektion 2', 'A1.1', 'Na ja.', 'none', NULL, 'Ну так…', 'İşte… / Eh.', 'Well… / Not really.', false, false),
('Lektion 2', 'A1.1', 'nicht so gut', 'none', NULL, 'не очень хорошо', 'pek iyi değil', 'not so good', false, false),
('Lektion 2', 'A1.1', 'sehr', 'none', NULL, 'очень', 'çok', 'very', false, false),
-- Familie
('Lektion 2', 'A1.1', 'Familie', 'die', 'Familien', 'семья', 'aile', 'family', false, false),
('Lektion 2', 'A1.1', 'Vater', 'der', 'Väter', 'отец', 'baba', 'father', true, true),
('Lektion 2', 'A1.1', 'Mutter', 'die', 'Mütter', 'мать', 'anne', 'mother', true, true),
('Lektion 2', 'A1.1', 'Eltern', 'die', NULL, 'родители', 'anne baba / ebeveynler', 'parents', false, false),
('Lektion 2', 'A1.1', 'Papa', 'der', 'Papas', 'папа', 'baba', 'dad', false, false),
('Lektion 2', 'A1.1', 'Mama', 'die', 'Mamas', 'мама', 'anne / mama', 'mom', false, false),
('Lektion 2', 'A1.1', 'Opa', 'der', 'Opas', 'дедушка', 'dede', 'grandpa', false, false),
('Lektion 2', 'A1.1', 'Oma', 'die', 'Omas', 'бабушка', 'anneanne / babaanne', 'grandma', false, false),
('Lektion 2', 'A1.1', 'Großeltern', 'die', NULL, 'бабушка и дедушка', 'büyükanne ve büyükbaba', 'grandparents', false, false),
('Lektion 2', 'A1.1', 'Bruder', 'der', 'Brüder', 'брат', 'erkek kardeş', 'brother', true, true),
('Lektion 2', 'A1.1', 'Schwester', 'die', 'Schwestern', 'сестра', 'kız kardeş', 'sister', false, false),
('Lektion 2', 'A1.1', 'Geschwister', 'die', NULL, 'братья и сёстры', 'kardeşler', 'siblings', false, false),
('Lektion 2', 'A1.1', 'Sohn', 'der', 'Söhne', 'сын', 'oğul / erkek çocuk', 'son', true, true),
('Lektion 2', 'A1.1', 'Tochter', 'die', 'Töchter', 'дочь', 'kız / kız çocuk', 'daughter', true, true),
('Lektion 2', 'A1.1', 'Kind', 'das', 'Kinder', 'ребёнок', 'çocuk', 'child', true, false),
('Lektion 2', 'A1.1', 'Enkel', 'der', 'Enkel', 'внук', 'erkek torun', 'grandson', false, false),
('Lektion 2', 'A1.1', 'Enkelin', 'die', 'Enkelinnen', 'внучка', 'kız torun', 'granddaughter', false, false),
('Lektion 2', 'A1.1', 'Mann', 'der', 'Männer', 'мужчина / муж', 'adam / koca', 'man / husband', true, true),
('Lektion 2', 'A1.1', 'Frau', 'die', 'Frauen', 'женщина / жена', 'kadın / eş', 'woman / wife', false, false),
('Lektion 2', 'A1.1', 'Ehefrau', 'die', 'Ehefrauen', 'супруга', 'eş (kadın)', 'wife', false, false),
('Lektion 2', 'A1.1', 'Lehrer', 'der', 'Lehrer', 'учитель', 'öğretmen (erkek)', 'teacher (male)', false, false),
('Lektion 2', 'A1.1', 'Lehrerin', 'die', 'Lehrerinnen', 'учительница', 'öğretmen (kadın)', 'teacher (female)', false, false),
-- Andere Nomen
('Lektion 2', 'A1.1', 'Pause', 'die', 'Pausen', 'перерыв', 'ara', 'break', false, false),
('Lektion 2', 'A1.1', 'Park', 'der', 'Parks', 'парк', 'park', 'park', false, false),
('Lektion 2', 'A1.1', 'Jahr', 'das', 'Jahre', 'год', 'yıl', 'year', true, false),
('Lektion 2', 'A1.1', 'Hauptstadt', 'die', 'Hauptstädte', 'столица', 'başkent', 'capital city', true, true),
('Lektion 2', 'A1.1', 'Ort', 'der', 'Orte', 'место / населённый пункт', 'yer / kasaba', 'place / town', false, false),
-- Verben
('Lektion 2', 'A1.1', 'lernen', 'none', NULL, 'учить / учиться', 'öğrenmek', 'to learn', false, false),
('Lektion 2', 'A1.1', 'leben', 'none', NULL, 'жить', 'yaşamak', 'to live', false, false),
('Lektion 2', 'A1.1', 'wohnen', 'none', NULL, 'проживать / жить (по адресу)', 'oturmak / ikamet etmek', 'to live (reside)', false, false),
('Lektion 2', 'A1.1', 'verstehen', 'none', NULL, 'понимать', 'anlamak', 'to understand', false, false),
('Lektion 2', 'A1.1', 'meinen', 'none', NULL, 'иметь в виду (Was meinen Sie?)', 'demek istemek (Ne demek istiyorsunuz?)', 'to mean', false, false),
-- Possessivartikel
('Lektion 2', 'A1.1', 'mein / meine', 'none', NULL, 'мой / моя / моё', 'benim', 'my', false, true),
('Lektion 2', 'A1.1', 'dein / deine', 'none', NULL, 'твой / твоя / твоё', 'senin', 'your (informal)', false, true),
('Lektion 2', 'A1.1', 'Ihr / Ihre', 'none', NULL, 'ваш / ваша / ваше (вежл.)', 'sizin (resmi)', 'your (formal)', false, true),
-- Personalpronomen
('Lektion 2', 'A1.1', 'er', 'none', NULL, 'он', 'o (erkek)', 'he', false, false),
('Lektion 2', 'A1.1', 'sie', 'none', NULL, 'она', 'o (kadın)', 'she', false, false),
('Lektion 2', 'A1.1', 'wir', 'none', NULL, 'мы', 'biz', 'we', false, false),
('Lektion 2', 'A1.1', 'ihr', 'none', NULL, 'вы (мн. ч., неформ.)', 'siz (çoğul, samimi)', 'you (plural, informal)', false, true),
('Lektion 2', 'A1.1', 'sie (Plural)', 'none', NULL, 'они', 'onlar', 'they', false, false),
-- Adjektive / Angaben
('Lektion 2', 'A1.1', 'alt', 'none', NULL, 'старый / … Jahre alt', 'yaşlı / … yaşında', 'old / … years old', false, false),
('Lektion 2', 'A1.1', 'gut', 'none', NULL, 'хороший / хорошо', 'iyi', 'good', false, false),
('Lektion 2', 'A1.1', 'verheiratet', 'none', NULL, 'женат / замужем', 'evli', 'married', false, false),
('Lektion 2', 'A1.1', 'geschieden', 'none', NULL, 'в разводе', 'boşanmış', 'divorced', false, false),
('Lektion 2', 'A1.1', 'getrennt', 'none', NULL, 'в раздельном проживании', 'ayrı', 'separated', false, false),
('Lektion 2', 'A1.1', 'keine', 'none', NULL, 'никакие / нет (Ich habe keine Geschwister.)', 'hiç / yok (Kardeşim yok.)', 'no / none', false, false),
('Lektion 2', 'A1.1', 'in', 'none', NULL, 'в', '…-de / …-da', 'in', false, false),
-- Zahlen 0–20
('Lektion 2', 'A1.1', 'null', 'none', NULL, 'ноль', 'sıfır', 'zero', false, false),
('Lektion 2', 'A1.1', 'eins', 'none', NULL, 'один', 'bir', 'one', false, false),
('Lektion 2', 'A1.1', 'zwei', 'none', NULL, 'два', 'iki', 'two', false, false),
('Lektion 2', 'A1.1', 'drei', 'none', NULL, 'три', 'üç', 'three', false, false),
('Lektion 2', 'A1.1', 'vier', 'none', NULL, 'четыре', 'dört', 'four', false, false),
('Lektion 2', 'A1.1', 'fünf', 'none', NULL, 'пять', 'beş', 'five', false, false),
('Lektion 2', 'A1.1', 'sechs', 'none', NULL, 'шесть', 'altı', 'six', false, false),
('Lektion 2', 'A1.1', 'sieben', 'none', NULL, 'семь', 'yedi', 'seven', false, false),
('Lektion 2', 'A1.1', 'acht', 'none', NULL, 'восемь', 'sekiz', 'eight', false, false),
('Lektion 2', 'A1.1', 'neun', 'none', NULL, 'девять', 'dokuz', 'nine', false, false),
('Lektion 2', 'A1.1', 'zehn', 'none', NULL, 'десять', 'on', 'ten', false, false),
('Lektion 2', 'A1.1', 'elf', 'none', NULL, 'одиннадцать', 'on bir', 'eleven', false, false),
('Lektion 2', 'A1.1', 'zwölf', 'none', NULL, 'двенадцать', 'on iki', 'twelve', false, false),
('Lektion 2', 'A1.1', 'dreizehn', 'none', NULL, 'тринадцать', 'on üç', 'thirteen', false, false),
('Lektion 2', 'A1.1', 'vierzehn', 'none', NULL, 'четырнадцать', 'on dört', 'fourteen', false, false),
('Lektion 2', 'A1.1', 'fünfzehn', 'none', NULL, 'пятнадцать', 'on beş', 'fifteen', false, false),
('Lektion 2', 'A1.1', 'sechzehn', 'none', NULL, 'шестнадцать', 'on altı', 'sixteen', false, false),
('Lektion 2', 'A1.1', 'siebzehn', 'none', NULL, 'семнадцать', 'on yedi', 'seventeen', false, false),
('Lektion 2', 'A1.1', 'achtzehn', 'none', NULL, 'восемнадцать', 'on sekiz', 'eighteen', false, false),
('Lektion 2', 'A1.1', 'neunzehn', 'none', NULL, 'девятнадцать', 'on dokuz', 'nineteen', false, false),
('Lektion 2', 'A1.1', 'zwanzig', 'none', NULL, 'двадцать', 'yirmi', 'twenty', false, false),
-- Wichtige Sätze
('Lektion 2', 'A1.1', 'Das ist mein Bruder.', 'none', NULL, 'Это мой брат.', 'Bu benim erkek kardeşim.', 'This is my brother.', false, false),
('Lektion 2', 'A1.1', 'Das ist meine Mutter.', 'none', NULL, 'Это моя мама.', 'Bu benim annem.', 'This is my mother.', false, false),
('Lektion 2', 'A1.1', 'Hast du Geschwister?', 'none', NULL, 'У тебя есть братья или сёстры?', 'Kardeşin var mı?', 'Do you have siblings?', false, false),
('Lektion 2', 'A1.1', 'Ich habe keine Geschwister.', 'none', NULL, 'У меня нет братьев и сестёр.', 'Kardeşim yok.', 'I have no siblings.', false, false),
('Lektion 2', 'A1.1', 'Wie alt bist du? – Ich bin 20 Jahre alt.', 'none', NULL, 'Сколько тебе лет? – Мне 20 лет.', 'Kaç yaşındasın? – 20 yaşındayım.', 'How old are you? – I am 20 years old.', false, false),
('Lektion 2', 'A1.1', 'Wo lebt deine Familie? – Meine Familie lebt in …', 'none', NULL, 'Где живёт твоя семья? – Моя семья живёт в …', 'Ailen nerede yaşıyor? – Ailem ...de yaşıyor.', 'Where does your family live? – My family lives in …', false, false),
('Lektion 2', 'A1.1', 'Meine Eltern sind verheiratet / geschieden', 'none', NULL, 'Мои родители женаты / в разводе', 'Annem ve babam evli / boşanmış', 'My parents are married / divorced', false, false);
